

kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1
metadata:
  name: caches.kuroboros.io
spec:
  group: kuroboros.io
  names:
    kind: Cache
    plural: caches
    shortNames: []
    singular: cache
  scope: Namespaced
  versions:
  - name: v1beta1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        description: |-
          Defines a Cache resource in kubernetes.
          A Cache resource is a Deployment of certain image, validated at creation
        type: object
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            type: object
            description: |-
              Defines the specifications
              of the Cache V1Beta1 Resource
            required:
            - engine
            - engineVersion
            - desiredSize
            properties:
              engine:
                type: string
                enum: ['redis', 'valkey', 'memcached']
                description: "The engine that will be deployed"
              engineVersion:
                type: string
                description: "The tag to use in the engine deployment image"
              desiredSize:
                type: integer
                minimum: 1
                description: "The desired number of replicas of the deployment"
              resources:
                type: object
                description: |-
                  Defines the limits ands requests of resources for the
                  Cache
                required:
                - requests
                - limits
                properties:
                  requests:
                    type: object
                    required:
                    - cpu
                    - memory
                    properties:
                      cpu:
                        type: string
                      memory:
                        type: string
                  limits:
                    type: object
                    required:
                    - cpu
                    - memory
                    properties:
                      cpu:
                        type: string
                      memory:
                        type: string
          status:
            type: object
            description: |-
              Defines the current phase and conditions
              of the Cache resource
            required: []
            properties:
              phase:
                type: string
                enum: ['Progressing', 'Healthy']
              conditions:
                type: array
                items:
                  type: object
                  required:
                  - status
                  - type
                  description: "Defines the conditions in the Cache"
                  properties:
                    lastTransitionTime:
                      type: string
                      format: date-time
                    message:
                      type: string
                    reason:
                      type: string
                    status:
                      type: string
                      enum: ['True', 'False', 'Unknown']
                    type:
                      type: string
                x-kubernetes-list-map-keys: ['type']
                x-kubernetes-list-type: map
              currentSize:
                type: integer
                minimum: 0