kind: Cache
apiVersion: kuroboros.io/v1beta1
metadata:
  name: test
  namespace: default
spec:
  engine: redis
  engineVersion: "latest"
  desiredSize: 1
  resources:
    requests:
      cpu: "1"
      memory: "2Gi"
    limits:
      cpu: "1.5"
      memory: "2Gi"
