apiVersion: v1
kind: Service
metadata:
  name: cache-operator-metrics
  namespace: cache-operator
  labels:
    app: cache-operator
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: metrics
  selector:
    app: cache-operator